- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python-jobs
      - publish-to-pypi
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
